[2025-08-11T13:06:44.621+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:06:44.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:06:44.629+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:06:44.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:06:44.707+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:06:45.168+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:06:45.168+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:06:45.232+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:06:45.232+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:06:45.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.682 seconds
[2025-08-11T13:07:20.002+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:07:20.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:07:20.262+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:07:20.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:07:20.600+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:07:20.843+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:07:20.842+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:07:20.998+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:07:20.997+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:07:21.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 1.541 seconds
[2025-08-11T13:07:51.290+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:07:51.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:07:51.296+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:07:51.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:07:51.341+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:07:51.392+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:07:51.392+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:07:51.421+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:07:51.421+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:07:51.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.176 seconds
[2025-08-11T13:08:21.518+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:08:21.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:08:21.523+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:08:21.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:08:21.584+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:08:21.649+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:08:21.648+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:08:21.690+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:08:21.690+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:08:21.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.209 seconds
[2025-08-11T13:08:51.925+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:08:51.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:08:51.929+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:08:51.929+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:08:51.960+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:08:51.993+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:08:51.993+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:08:52.024+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:08:52.023+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:08:52.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.137 seconds
[2025-08-11T13:09:22.182+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:09:22.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:09:22.188+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:09:22.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:09:22.252+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:09:22.307+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:09:22.306+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:09:22.354+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:09:22.353+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:09:22.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.215 seconds
[2025-08-11T13:09:52.536+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:09:52.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:09:52.547+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:09:52.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:09:52.592+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:09:52.648+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:09:52.647+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:09:52.712+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:09:52.712+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:09:52.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.233 seconds
[2025-08-11T13:10:22.853+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:10:22.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:10:22.858+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:10:22.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:10:22.885+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:10:22.915+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:10:22.915+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:10:22.944+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:10:22.944+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:10:22.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.126 seconds
[2025-08-11T13:10:53.224+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:10:53.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:10:53.230+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:10:53.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:10:53.268+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:10:53.309+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:10:53.308+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:10:53.342+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:10:53.341+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:10:53.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.158 seconds
[2025-08-11T13:11:23.443+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:11:23.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:11:23.447+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:11:23.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:11:23.473+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:11:23.500+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:11:23.500+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:11:23.527+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:11:23.527+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:11:23.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.122 seconds
[2025-08-11T13:11:53.702+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:11:53.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:11:53.706+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:11:53.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:11:53.734+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:11:53.762+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:11:53.762+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:11:53.796+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:11:53.796+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:11:53.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.149 seconds
[2025-08-11T13:12:24.004+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:12:24.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:12:24.009+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:12:24.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:12:24.038+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:12:24.065+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:12:24.065+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:12:24.091+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:12:24.090+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:12:24.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.122 seconds
[2025-08-11T13:12:54.291+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:12:54.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:12:54.295+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:12:54.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:12:54.328+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:12:54.377+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:12:54.376+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:12:54.437+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:12:54.437+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:12:54.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.186 seconds
[2025-08-11T13:13:24.564+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:13:24.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:13:24.568+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:13:24.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:13:24.597+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:13:24.626+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:13:24.625+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:13:24.649+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:13:24.649+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:13:24.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.130 seconds
[2025-08-11T13:13:55.138+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:13:55.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:13:55.154+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:13:55.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:13:55.262+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:13:55.435+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:13:55.434+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:13:55.577+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:13:55.577+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:13:55.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.626 seconds
[2025-08-11T13:14:25.993+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:14:26.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:14:26.020+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:14:26.019+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:14:26.108+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:14:26.142+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:14:26.141+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:14:26.178+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:14:26.178+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:14:26.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.236 seconds
[2025-08-11T13:14:56.875+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:14:56.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:14:56.879+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:14:56.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:14:57.103+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:14:57.135+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:14:57.135+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:14:57.169+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:14:57.168+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:14:57.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 1.017 seconds
[2025-08-11T13:15:28.264+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:15:28.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:15:28.269+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:15:28.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:15:28.323+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:15:28.378+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:15:28.378+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:15:28.412+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:15:28.412+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:15:28.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.189 seconds
[2025-08-11T13:15:58.518+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:15:58.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:15:58.525+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:15:58.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:15:58.580+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:15:58.649+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:15:58.648+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:15:58.682+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:15:58.681+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:15:58.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.206 seconds
[2025-08-11T13:16:28.967+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:16:28.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:16:28.974+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:16:28.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:16:29.032+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:16:29.116+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:16:29.116+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:16:29.148+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:16:29.148+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:16:29.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.225 seconds
[2025-08-11T13:16:59.294+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:16:59.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:16:59.300+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:16:59.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:16:59.347+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:16:59.407+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:16:59.406+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:16:59.442+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:16:59.442+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:16:59.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.192 seconds
[2025-08-11T13:17:29.691+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:17:29.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:17:29.695+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:17:29.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:17:29.772+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:17:29.904+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:17:29.904+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:17:29.954+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:17:29.953+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:17:30.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.334 seconds
[2025-08-11T13:18:00.524+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:18:00.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:18:00.530+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:18:00.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:18:00.607+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:18:06.148+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:18:06.141+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:18:06.188+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:18:06.188+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:18:06.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 5.708 seconds
[2025-08-11T13:18:36.458+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:18:36.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:18:36.477+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:18:36.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:18:37.104+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:18:54.549+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:18:54.544+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:18:54.585+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:18:54.584+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:18:54.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 18.326 seconds
[2025-08-11T13:19:25.542+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:19:25.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:19:25.549+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:19:25.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:19:25.622+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:19:27.462+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:19:27.455+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:19:27.503+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:19:27.503+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:19:27.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 2.010 seconds
[2025-08-11T13:19:58.064+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:19:58.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:19:58.073+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:19:58.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:19:58.189+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:20:29.485+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-08-11T13:20:59.796+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:20:59.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:20:59.800+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:20:59.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:20:59.870+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:21:00.542+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:21:00.542+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:21:00.582+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:21:00.581+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:21:00.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.840 seconds
[2025-08-11T13:21:31.311+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:21:31.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:21:31.316+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:21:31.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:21:31.385+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:21:31.546+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:21:31.546+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:21:31.581+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:21:31.581+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:21:31.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.312 seconds
[2025-08-11T13:22:01.728+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:22:01.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:22:01.739+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:22:01.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:22:01.999+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:22:02.888+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:22:02.878+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:22:02.958+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:22:02.957+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:22:03.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 1.313 seconds
[2025-08-11T13:22:33.185+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:22:33.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:22:33.189+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:22:33.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:22:33.258+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:22:33.370+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:22:33.370+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:22:33.408+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:22:33.408+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:22:33.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.270 seconds
[2025-08-11T13:23:04.132+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:23:04.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:23:04.142+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:23:04.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:23:04.247+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:23:34.838+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-08-11T13:24:05.187+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:24:05.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:24:05.192+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:24:05.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:24:05.261+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:24:05.644+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:24:05.644+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:24:05.681+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:24:05.681+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:24:05.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.546 seconds
[2025-08-11T13:24:36.241+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:24:36.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:24:36.245+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:24:36.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:24:36.305+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:24:36.423+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:24:36.422+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:24:36.456+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:24:36.456+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:24:36.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.258 seconds
[2025-08-11T13:25:06.867+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:06.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:25:06.872+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:25:06.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:06.939+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:07.067+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:25:07.066+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:25:07.099+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:25:07.099+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:25:07.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.280 seconds
[2025-08-11T13:25:11.251+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:11.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:25:11.254+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:25:11.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:11.312+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:11.638+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:25:11.638+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:25:11.671+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:25:11.670+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:25:11.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.474 seconds
[2025-08-11T13:25:41.903+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:41.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:25:41.914+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:25:41.909+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:25:42.341+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:26:14.222+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-08-11T13:27:16.732+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:27:16.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:27:16.747+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:27:16.739+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:27:16.991+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:29:59.466+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:29:59.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:29:59.483+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:29:59.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:29:59.583+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:30:00.184+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:30:00.183+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:30:00.251+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:30:00.250+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:30:00.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.873 seconds
[2025-08-11T13:30:32.231+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:30:32.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:30:32.268+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:30:32.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:30:32.632+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:30:32.906+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:30:32.906+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:30:33.710+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:30:33.709+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:30:33.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 1.688 seconds
[2025-08-11T13:31:04.622+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:31:04.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:31:04.803+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:31:04.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:31:06.500+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:31:07.110+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:31:07.109+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:31:07.121+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:31:07.121+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:31:07.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 2.653 seconds
[2025-08-11T13:31:37.633+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:31:37.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:31:37.639+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:31:37.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:31:37.691+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:31:37.837+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:31:37.837+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:31:37.878+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:31:37.877+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:31:37.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.296 seconds
[2025-08-11T13:32:07.991+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:07.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:32:07.995+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:07.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:08.026+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:08.056+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:08.056+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:32:08.083+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:08.083+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:32:08.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.137 seconds
[2025-08-11T13:32:38.255+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:38.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:32:38.259+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:38.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:38.291+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:38.330+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:38.329+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:32:38.367+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:38.367+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:32:38.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.154 seconds
[2025-08-11T13:32:43.499+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:43.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:32:43.504+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:43.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:43.562+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:32:43.607+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:43.607+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:32:43.641+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:32:43.640+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:32:43.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.196 seconds
[2025-08-11T13:33:13.766+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:33:13.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:33:13.781+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:33:13.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:33:13.836+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:33:13.987+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:33:13.985+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:33:14.059+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:33:14.059+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:33:14.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.356 seconds
[2025-08-11T13:33:44.365+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:33:44.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:33:44.372+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:33:44.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:33:44.416+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:33:44.471+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:33:44.471+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:33:44.502+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:33:44.502+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:33:44.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.177 seconds
[2025-08-11T13:34:15.418+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:34:15.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:34:15.436+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:34:15.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:34:15.508+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:34:15.632+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:34:15.631+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:34:15.678+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:34:15.677+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:34:15.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.317 seconds
[2025-08-11T13:34:45.921+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:34:45.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:34:45.929+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:34:45.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:34:46.076+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:34:46.187+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:34:46.186+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:34:46.233+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:34:46.232+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:34:46.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.370 seconds
[2025-08-11T13:35:16.599+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:35:16.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:35:16.608+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:35:16.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:35:16.669+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:35:16.763+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:35:16.762+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:35:16.858+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:35:16.857+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:35:16.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.325 seconds
[2025-08-11T13:35:47.165+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:35:47.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T13:35:47.170+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:35:47.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:35:47.202+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T13:35:47.238+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:35:47.238+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T13:35:47.268+0000] {logging_mixin.py:188} INFO - [2025-08-11T13:35:47.268+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T13:35:47.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.143 seconds
[2025-08-11T14:01:29.880+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:01:30.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:01:31.453+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:01:31.452+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:01:31.964+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:01:32.552+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:01:32.551+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:bank_data_generation_dag
[2025-08-11T14:01:32.578+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:01:32.578+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:bank_data_generation_dag
[2025-08-11T14:01:32.598+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:01:32.598+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:bank_data_generation_dag
[2025-08-11T14:01:32.600+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:01:32.599+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:01:32.616+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:01:32.615+0000] {dag.py:3058} INFO - Creating ORM DAG for bank_data_generation_dag
[2025-08-11T14:01:32.637+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:01:32.636+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T14:01:32.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 4.070 seconds
[2025-08-11T14:02:03.735+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:02:03.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:02:04.050+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:02:04.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:02:07.229+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:02:08.991+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:02:08.990+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:02:09.247+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:02:09.247+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:02:09.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 5.979 seconds
[2025-08-11T14:02:40.313+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:02:40.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:02:40.321+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:02:40.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:02:40.384+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:02:40.478+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:02:40.478+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:02:40.560+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:02:40.559+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:02:40.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.317 seconds
[2025-08-11T14:03:10.931+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:03:10.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:03:10.939+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:03:10.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:03:11.017+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:03:11.094+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:03:11.094+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:03:11.166+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:03:11.165+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:03:11.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.317 seconds
[2025-08-11T14:03:41.581+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:03:41.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:03:41.594+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:03:41.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:03:41.694+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:03:41.838+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:03:41.838+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:03:41.971+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:03:41.971+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:03:42.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.518 seconds
[2025-08-11T14:04:12.585+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:04:12.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:04:12.592+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:04:12.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:04:12.645+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:04:13.136+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:04:13.135+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:04:13.171+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:04:13.171+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:04:13.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.632 seconds
[2025-08-11T14:04:43.482+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:04:43.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:04:43.490+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:04:43.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:04:43.539+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:04:43.612+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:04:43.612+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:04:43.646+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:04:43.645+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:04:43.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.210 seconds
[2025-08-11T14:05:13.751+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:05:13.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:05:13.758+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:05:13.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:05:13.819+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:05:13.934+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:05:13.933+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:05:13.969+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:05:13.968+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:05:14.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.262 seconds
[2025-08-11T14:05:44.290+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:05:44.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:05:44.300+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:05:44.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:05:44.397+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:05:44.629+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:05:44.614+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:05:44.795+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:05:44.793+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:05:44.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.589 seconds
[2025-08-11T14:06:15.185+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:06:15.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:06:15.194+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:06:15.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:06:15.288+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:06:15.565+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:06:15.557+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:06:15.621+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:06:15.621+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:06:15.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.497 seconds
[2025-08-11T14:06:45.855+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:06:45.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:06:45.873+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:06:45.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:06:45.957+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:06:46.239+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:06:46.239+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:06:46.291+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:06:46.290+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:06:46.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.497 seconds
[2025-08-11T14:07:16.610+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:07:16.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:07:16.618+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:07:16.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:07:16.676+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:07:17.076+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:07:17.066+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:07:17.069+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:07:17.068+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:07:17.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.570 seconds
[2025-08-11T14:07:47.365+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:07:47.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:07:47.373+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:07:47.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:07:47.455+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:07:47.642+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:07:47.642+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:07:47.701+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:07:47.700+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:07:47.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.398 seconds
[2025-08-11T14:08:18.087+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:08:18.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:08:18.096+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:08:18.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:08:18.184+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:08:18.389+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:08:18.389+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:08:18.430+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:08:18.429+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:08:18.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.397 seconds
[2025-08-11T14:08:48.799+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:08:48.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:08:48.807+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:08:48.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:08:48.882+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:08:49.060+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:08:49.059+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:08:49.109+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:08:49.109+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:08:49.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.360 seconds
[2025-08-11T14:09:00.373+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:09:00.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:09:00.380+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:09:00.378+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:09:00.445+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:09:00.540+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:09:00.539+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:09:00.574+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:09:00.573+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:09:00.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.256 seconds
[2025-08-11T14:09:30.883+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:09:30.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:09:30.890+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:09:30.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:09:30.942+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:09:31.024+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:09:31.024+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:09:31.071+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:09:31.070+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:09:31.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.231 seconds
[2025-08-11T14:45:11.742+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:45:11.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:45:11.750+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:11.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:45:11.872+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:45:12.382+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:12.381+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:bank_data_generation_dag
[2025-08-11T14:45:12.407+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:12.407+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:bank_data_generation_dag
[2025-08-11T14:45:12.424+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:12.423+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:bank_data_generation_dag
[2025-08-11T14:45:12.425+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:12.425+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:45:12.439+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:12.439+0000] {dag.py:3058} INFO - Creating ORM DAG for bank_data_generation_dag
[2025-08-11T14:45:12.455+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:12.455+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 13:00:00+00:00, run_after=2025-08-11 14:00:00+00:00
[2025-08-11T14:45:12.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.780 seconds
[2025-08-11T14:45:44.407+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:45:44.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:45:44.490+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:44.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:45:44.638+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:45:44.748+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:44.747+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:45:48.067+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:45:48.067+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:45:48.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 4.053 seconds
[2025-08-11T14:46:19.102+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:46:19.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:46:19.111+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:46:19.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:46:19.165+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:46:19.223+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:46:19.223+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:46:22.178+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:46:22.144+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:46:23.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 3.990 seconds
[2025-08-11T14:46:53.680+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:46:53.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:46:53.705+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:46:53.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:46:55.858+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:46:58.410+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:46:58.409+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:46:58.791+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:46:58.791+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:46:58.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 5.236 seconds
[2025-08-11T14:47:33.500+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:47:34.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:47:34.969+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:47:34.724+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:50:50.198+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:50:50.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:50:50.267+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:50:50.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:51:00.347+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:57:03.645+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:57:03.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:57:03.652+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:57:03.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:57:03.721+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:57:03.769+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:57:03.768+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:57:03.825+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:57:03.825+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:57:03.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.232 seconds
[2025-08-11T14:57:33.982+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:57:33.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:57:33.990+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:57:33.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:57:34.071+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:57:37.789+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:57:37.788+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:57:37.858+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:57:37.857+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:57:37.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 3.944 seconds
[2025-08-11T14:58:08.210+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:58:08.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:58:08.216+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:58:08.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:58:08.278+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:58:08.376+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:58:08.375+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:58:08.410+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:58:08.410+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:58:08.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.243 seconds
[2025-08-11T14:58:38.610+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:58:38.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:58:38.619+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:58:38.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:58:38.696+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:59:00.420+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:59:00.413+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T14:59:00.468+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:59:00.467+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 14:00:00+00:00, run_after=2025-08-11 15:00:00+00:00
[2025-08-11T14:59:00.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 21.899 seconds
[2025-08-11T14:59:30.625+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:59:30.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T14:59:30.637+0000] {logging_mixin.py:188} INFO - [2025-08-11T14:59:30.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T14:59:30.730+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:00:02.310+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-08-11T15:00:33.337+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:00:33.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:00:33.342+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:00:33.341+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:00:33.411+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:00:44.407+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:00:44.401+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:00:44.454+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:00:44.454+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:00:44.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 11.168 seconds
[2025-08-11T15:01:14.733+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:01:14.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:01:14.778+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:01:14.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:01:29.760+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:01:51.414+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:01:51.407+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:01:51.450+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:01:51.450+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:01:51.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 36.846 seconds
[2025-08-11T15:02:22.457+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:02:22.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:02:22.464+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:02:22.461+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:02:22.534+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:02:32.045+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:02:32.039+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:02:32.084+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:02:32.083+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:02:32.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 9.666 seconds
[2025-08-11T15:03:02.276+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:03:02.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:03:02.284+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:03:02.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:03:02.374+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:03:02.583+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:03:02.582+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:03:02.668+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:03:02.668+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:03:02.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.453 seconds
[2025-08-11T15:03:33.252+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:03:33.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:03:33.258+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:03:33.256+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:03:33.332+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:03:33.449+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:03:33.448+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:03:33.486+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:03:33.486+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:03:33.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.285 seconds
[2025-08-11T15:04:03.659+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:04:03.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:04:03.761+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:04:03.718+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:04:04.240+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:04:35.520+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-08-11T15:05:11.816+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:05:11.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:05:11.947+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:05:11.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:05:31.627+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:05:55.676+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:05:55.671+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:05:55.720+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:05:55.719+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:05:55.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 44.028 seconds
[2025-08-11T15:06:02.165+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:06:02.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:06:02.170+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:06:02.235+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:06:02.329+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.329+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'bank_data_generation_dag', 'Task Id': 'generate_bank_data', 'Run Id': 'scheduled__2025-08-11T14:00:00+00:00', 'Hostname': 'dac0489f31c3', 'External Executor Id': '900b8ae6-3398-4ce9-8e93-7db26013cfb7'}
[2025-08-11T15:06:02.373+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.372+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bank_data_generation_dag, task_id=generate_bank_data, execution_date=20250811T140000, start_date=20250811T150015, end_date=20250811T150602
[2025-08-11T15:06:02.394+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: bank_data_generation_dag.generate_bank_data scheduled__2025-08-11T14:00:00+00:00 [failed]> in state failed
[2025-08-11T15:06:02.398+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.398+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'bank_data_generation_dag', 'Task Id': 'generate_bank_data', 'Run Id': 'scheduled__2025-08-11T14:00:00+00:00', 'Hostname': 'dac0489f31c3', 'External Executor Id': '900b8ae6-3398-4ce9-8e93-7db26013cfb7'}
[2025-08-11T15:06:02.410+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.410+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bank_data_generation_dag, task_id=generate_bank_data, execution_date=20250811T140000, start_date=20250811T150015, end_date=20250811T150602
[2025-08-11T15:06:02.417+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: bank_data_generation_dag.generate_bank_data scheduled__2025-08-11T14:00:00+00:00 [failed]> in state failed
[2025-08-11T15:06:02.421+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.420+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'bank_data_generation_dag', 'Task Id': 'generate_bank_data', 'Run Id': 'scheduled__2025-08-11T14:00:00+00:00', 'Hostname': 'dac0489f31c3', 'External Executor Id': '900b8ae6-3398-4ce9-8e93-7db26013cfb7'}
[2025-08-11T15:06:02.431+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.431+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bank_data_generation_dag, task_id=generate_bank_data, execution_date=20250811T140000, start_date=20250811T150015, end_date=20250811T150602
[2025-08-11T15:06:02.437+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: bank_data_generation_dag.generate_bank_data scheduled__2025-08-11T14:00:00+00:00 [failed]> in state failed
[2025-08-11T15:06:02.441+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.441+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'bank_data_generation_dag', 'Task Id': 'generate_bank_data', 'Run Id': 'scheduled__2025-08-11T14:00:00+00:00', 'Hostname': 'dac0489f31c3', 'External Executor Id': '900b8ae6-3398-4ce9-8e93-7db26013cfb7'}
[2025-08-11T15:06:02.452+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.452+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bank_data_generation_dag, task_id=generate_bank_data, execution_date=20250811T140000, start_date=20250811T150015, end_date=20250811T150602
[2025-08-11T15:06:02.458+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: bank_data_generation_dag.generate_bank_data scheduled__2025-08-11T14:00:00+00:00 [failed]> in state failed
[2025-08-11T15:06:02.471+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.470+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:06:02.493+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:02.492+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:06:02.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 0.365 seconds
[2025-08-11T15:06:32.784+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:06:32.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/bank_data_dag.py for tasks to queue
[2025-08-11T15:06:32.790+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:32.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:06:32.862+0000] {processor.py:840} INFO - DAG(s) 'bank_data_generation_dag' retrieved from /opt/airflow/dags/bank_data_dag.py
[2025-08-11T15:06:50.879+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:50.874+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-08-11T15:06:50.924+0000] {logging_mixin.py:188} INFO - [2025-08-11T15:06:50.923+0000] {dag.py:3823} INFO - Setting next_dagrun for bank_data_generation_dag to 2025-08-11 15:00:00+00:00, run_after=2025-08-11 16:00:00+00:00
[2025-08-11T15:06:50.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/bank_data_dag.py took 18.182 seconds
